#!/usr/bin/env node
/**
 * Build-time asset embedding: reads the version, runtime prompts and UI HTML,
 * and generates src/generated/assets.ts (escaped via JSON.stringify) so Node and Bun
 * consume them through the same mechanism.
 * Called by build.mjs (before tsc) and pack.mjs (before typecheck).
 */
import { mkdirSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { fileURLToPath } from "node:url";

const root = fileURLToPath(new URL("..", import.meta.url));
const outDir = join(root, "src", "generated");

const version = readFileSync(join(root, "version"), "utf8").trim();

const prompts = {};
for (const name of readdirSync(join(root, "src", "runtime", "prompts")).filter((entry) => entry.endsWith(".md"))) {
  prompts[name.replace(/\.md$/, "")] = readFileSync(join(root, "src", "runtime", "prompts", name), "utf8");
}

const ui = {};
for (const name of ["dashboard.html", "preview.html", "tasks.html"]) {
  ui[name] = readFileSync(join(root, "src", "ui", name), "utf8");
}

const content = `// This file is auto-generated by scripts/embed-assets.mjs; do not edit by hand.
export const EMBEDDED_VERSION: string = ${JSON.stringify(version)};
export const EMBEDDED_PROMPTS: Record<string, string> = ${JSON.stringify(prompts)};
export const EMBEDDED_UI: Record<string, string> = ${JSON.stringify(ui)};
`;

mkdirSync(outDir, { recursive: true });
writeFileSync(join(outDir, "assets.ts"), content);
process.stdout.write(`[embed-assets] generated src/generated/assets.ts (version ${version})\n`);
