#!/usr/bin/env node
/**
 * Build-time asset embedding: reads the version, runtime prompts and the UI
 * static site (html + styles/ + scripts/ + assets/), and generates
 * src/generated/assets.ts (escaped via JSON.stringify) so Node and Bun consume
 * them through the same mechanism.
 * Called by build.mjs (before tsc) and pack.mjs (before typecheck).
 */
import { mkdirSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { join, relative, sep } from "node:path";
import { fileURLToPath } from "node:url";

const root = fileURLToPath(new URL("..", import.meta.url));
const outDir = join(root, "src", "generated");

const version = readFileSync(join(root, "version"), "utf8").trim();

const prompts = {};
for (const name of readdirSync(join(root, "src", "runtime", "prompts")).filter((entry) => entry.endsWith(".md"))) {
  prompts[name.replace(/\.md$/, "")] = readFileSync(join(root, "src", "runtime", "prompts", name), "utf8");
}

// The UI is a small static site; embed every recognized asset, keyed by its
// posix-relative path, so serveDashboard can map request paths directly.
const UI_EXTENSIONS = new Set([
  ".html", ".css", ".js", ".mjs", ".json", ".svg", ".png", ".jpg", ".jpeg",
  ".gif", ".webp", ".ico", ".woff", ".woff2", ".map", ".txt",
]);
function walkUi(dir, out = []) {
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    // src/ui/app holds the TypeScript sources of the bundled UI; it is not
    // part of the served static site.
    if (entry.name === "app" && entry.isDirectory()) continue;
    const full = join(dir, entry.name);
    if (entry.isDirectory()) {
      walkUi(full, out);
    } else {
      const dot = entry.name.lastIndexOf(".");
      const ext = dot >= 0 ? entry.name.slice(dot) : "";
      if (UI_EXTENSIONS.has(ext)) out.push(full);
    }
  }
  return out;
}
const uiDir = join(root, "src", "ui");
const ui = {};
for (const file of walkUi(uiDir)) {
  ui[relative(uiDir, file).split(sep).join("/")] = readFileSync(file, "utf8");
}

const content = `// This file is auto-generated by scripts/embed-assets.mjs; do not edit by hand.
export const EMBEDDED_VERSION: string = ${JSON.stringify(version)};
export const EMBEDDED_PROMPTS: Record<string, string> = ${JSON.stringify(prompts)};
export const EMBEDDED_UI: Record<string, string> = ${JSON.stringify(ui)};
`;

mkdirSync(outDir, { recursive: true });
writeFileSync(join(outDir, "assets.ts"), content);
process.stdout.write(`[embed-assets] generated src/generated/assets.ts (version ${version}, ${Object.keys(ui).length} ui files)\n`);
